/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuelRouteImport } from './routes/fuel'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsVehiclesRouteImport } from './routes/settings/vehicles'
import { Route as SettingsPersonalInfoRouteImport } from './routes/settings/personal-info'
import { Route as SettingsDataPrivacyRouteImport } from './routes/settings/data-privacy'
import { Route as SettingsCategoriesRouteImport } from './routes/settings/categories'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsVehiclesRoute = SettingsVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPersonalInfoRoute = SettingsPersonalInfoRouteImport.update({
  id: '/personal-info',
  path: '/personal-info',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataPrivacyRoute = SettingsDataPrivacyRouteImport.update({
  id: '/data-privacy',
  path: '/data-privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/data-privacy': typeof SettingsDataPrivacyRoute
  '/settings/personal-info': typeof SettingsPersonalInfoRoute
  '/settings/vehicles': typeof SettingsVehiclesRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof TransactionsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/data-privacy': typeof SettingsDataPrivacyRoute
  '/settings/personal-info': typeof SettingsPersonalInfoRoute
  '/settings/vehicles': typeof SettingsVehiclesRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/data-privacy': typeof SettingsDataPrivacyRoute
  '/settings/personal-info': typeof SettingsPersonalInfoRoute
  '/settings/vehicles': typeof SettingsVehiclesRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/fuel'
    | '/login'
    | '/register'
    | '/settings'
    | '/transactions'
    | '/settings/categories'
    | '/settings/data-privacy'
    | '/settings/personal-info'
    | '/settings/vehicles'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/fuel'
    | '/login'
    | '/register'
    | '/transactions'
    | '/settings/categories'
    | '/settings/data-privacy'
    | '/settings/personal-info'
    | '/settings/vehicles'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/fuel'
    | '/login'
    | '/register'
    | '/settings'
    | '/transactions'
    | '/settings/categories'
    | '/settings/data-privacy'
    | '/settings/personal-info'
    | '/settings/vehicles'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  FuelRoute: typeof FuelRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/vehicles': {
      id: '/settings/vehicles'
      path: '/vehicles'
      fullPath: '/settings/vehicles'
      preLoaderRoute: typeof SettingsVehiclesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/personal-info': {
      id: '/settings/personal-info'
      path: '/personal-info'
      fullPath: '/settings/personal-info'
      preLoaderRoute: typeof SettingsPersonalInfoRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data-privacy': {
      id: '/settings/data-privacy'
      path: '/data-privacy'
      fullPath: '/settings/data-privacy'
      preLoaderRoute: typeof SettingsDataPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsDataPrivacyRoute: typeof SettingsDataPrivacyRoute
  SettingsPersonalInfoRoute: typeof SettingsPersonalInfoRoute
  SettingsVehiclesRoute: typeof SettingsVehiclesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsDataPrivacyRoute: SettingsDataPrivacyRoute,
  SettingsPersonalInfoRoute: SettingsPersonalInfoRoute,
  SettingsVehiclesRoute: SettingsVehiclesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  FuelRoute: FuelRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
